version: '3.7'


services:
    api:
        build: 
            context: ./api
            dockerfile: Dockerfile.prod
        command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/api/api/staticfiles
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - api

volumes:
    postgres_data:
    static_volume:
